Repository COSC481W-2024Fall/OurSpace, pull requests merged in 2024-11, with the labels that each got.

#27 User Profile
  public/EditUserPage.html
  public/fetchUserDataProfile.js
  public/firebaseAuth.js
  public/firebaseConfig.js
  public/homepage.html
  public/userpage.css
  public/userpage.js
Labels: enhancement, Sprint-2

#25 Started on password encryption.
  src/login/signup.css
  src/login/signup.html
  src/tests/login.test.js
Labels: Sprint-2

#28 Friend Profile and Homepage Adjustments
  firestore.rules
  public/firebasePost.js
  public/friendSearch.js
  public/friendprofile.css
  public/friendprofile.js
  public/friendsprofile.html
  public/homepage.css
  public/homepage.html
  public/homepage.js
  public/profile.js
  public/signup.css
  public/signup.html
  src/tests/friendprofile.test.js
  src/tests/homepage.test.js
Labels: enhancement, Feature

#33 Added Profile Images
  public/EditUserPage.html
  public/fetchUserDataProfile.js
  public/firebaseAuth.js
  public/userpage.css
  public/userpage.js
Labels: documentation, enhancement, Sprint-3

#35 Add Friend Feature, Dynamic Friends List, and Logo
  firestore.rules
  public/Blue+White long logo.png
  public/EditUserPage.html
  public/firebaseAuth.js
  public/firebaseLogin.js
  public/friendprofile.css
  public/friendsprofile.html
  public/homepage.css
  public/homepage.html
  public/homepage.js
  public/login.css
  public/login.html
  public/signup.css
  public/signup.html
  public/userpage.css
Labels: enhancement, Sprint-3, Feature

#36 Fixed our website to a more updated version of Firebase and changed the design
  public/EditUserPage.html
  public/firebaseAuth.js
  public/firebaseConfig.js
  public/firebaseLogin.js
  public/friendprofile.css
  public/friendsprofile.html
  public/homepage.css
  public/homepage.html
  public/login.css
  public/login.html
  public/signup.css
  public/signup.html
  public/userpage.css
  public/userpage.js
Labels: design, fixes
